chartmogul/chartmogul-node

test/chartmogul/plan.js

Easy, no new production code, just 2 tests on plan modification/destroying.

Adding mocked tests: plan (modify/destroy)

---

lib/chartmogul/invoice.js
package.json
test/chartmogul/invoice.js

* we now allow fetching all invoices across customers/data_sources.
* for the API user it will be unified experience - one method, backwards compatible
* either they pass a string (legacy), or object with parameters (or nothing), which will use the new endpoint

List invoices

---

lib/chartmogul/invoice.js
package.json
test/chartmogul/invoice.js

[DP-309] support for Delete Invoice

---

README.md
lib/chartmogul/invoice.js
package.json
test/chartmogul/invoice.js

[DP-468] Retrieve Invoice endpoint

---

lib/chartmogul/resource.js
package.json
test/chartmogul/ping.js
test/chartmogul/resource.js

[ch5147](https://app.clubhouse.io/chartmogul/story/5147/maintenance-of-dependencies)
Contains:
- fixed failing test
- updated deps (fixed `npm audit` criticals, high, medium, low, only 1 low remains)
- update package.json script name
- removed debug comments

[ch5147] Maintenance of deps

---

README.md
lib/chartmogul/metrics/customer.js
test/chartmogul/metrics/index.js

Story: [ch3037](https://app.clubhouse.io/chartmogul/story/3037/allow-pagination-on-customer-metrics)

Added pagination param to metrics [ch3037]

---

lib/chartmogul/resource.js

Story: [ch4272](https://app.clubhouse.io/chartmogul/story/4272/unhandledpromiserejectionwarning-in-latest-node-version)

Fix UnhandledPromiseRejectionWarning [ch4272]

---

.eslintrc
README.md
lib/chartmogul/resource.js
package-lock.json
package.json
test/chartmogul/resource.js

* Retry on 429, [500,600) statuses
* Retry on network releated errors
* Retry for maximum 15 mins

Added retry logic [ch3381]

---

.codeclimate.yml
README.md
lib/chartmogul/customer.js
test/chartmogul/customer.js

Added `connectSubscription` method: https://dev.chartmogul.com/reference#connect-subscriptions
Example:
```js
ChartMogul.Customer.connectSubscriptions(config, "cus_5915ee5a-babd-406b-b8ce-d207133fb4cb", {
"subscriptions": [{
"data_source_uuid": "ds_ade45e52-47a4-231a-1ed2-eb6b9e541213",
"external_id": "d1c0c885-add0-48db-8fa9-0bdf5017d6b0"
},
{
"data_source_uuid": "ds_ade45e52-47a4-231a-1ed2-eb6b9e541213",
"external_id": "9db5f4a1-1695-44c0-8bd4-de7ce4d0f1d4"
}
]
})
```

Added method for Connect subscriptions [ch4620]

---

.travis.yml
lib/chartmogul/invoice.js
lib/chartmogul/resource.js
lib/chartmogul/util/index.js
lib/chartmogul/util/retry.js
package-lock.json
package.json

* We already had a failing test case. But it was passing due to a bug in nock library. (see [fix](https://github.com/nock/nock/pull/829))
* Refactored a little to move retry logic to separate file

Fix bug with Invoice.all has query parameters [ch11270]

---

package-lock.json
package.json

Security fixes in 3 libraries, bumping up version.

Update libraries [ch9762]

---

README.md
lib/chartmogul.js
lib/chartmogul/plan-group-plans.js
lib/chartmogul/plan-group.js
package.json
test/chartmogul/plan-group.js

* add PlanGroup endpoints
```
GET /v1/plan_groups
GET /v1/plan_groups/plan_group_uuid
GET /v1/plan_groups/plan_group_uuid/plans
POST /v1/plan_groups/plan_group_uuid
PATCH /v1/plan_groups/plan_group_uuid
DELETE /v1/plan_groups/plan_group_uuid
```
* increment version
* add changes to README

Support for Plan Group API  [ch19227]

---

lib/chartmogul/invoice.js
package.json
test/chartmogul/invoice.js

This PR adds delete_all_invoices method to Invoice class

Add a method to delete all customer's invoices (ch23545)

---

README.md
lib/chartmogul/resource.js
package-lock.json
package.json

- Add deprecation info
- Run npm install & eslint

Add deprecation info [#35175]

---

README.md
lib/chartmogul/config.js
lib/chartmogul/resource.js
lib/chartmogul/util/retry.js
package-lock.json
package.json
test/chartmogul/account.js
test/chartmogul/custom-attribute.js
test/chartmogul/customer.js
test/chartmogul/data-source.js
test/chartmogul/enrichment/custom-attribute.js
test/chartmogul/enrichment/customer.js
test/chartmogul/enrichment/tag.js
test/chartmogul/errors/chartmogul-error.js
test/chartmogul/import/invoice.js
test/chartmogul/import/subscription.js
test/chartmogul/import/transaction.js
test/chartmogul/invoice.js
test/chartmogul/metrics/activities_export.js
test/chartmogul/metrics/activity.js
test/chartmogul/metrics/index.js
test/chartmogul/ping.js
test/chartmogul/plan-group.js
test/chartmogul/plan.js
test/chartmogul/resource.js
test/chartmogul/subscription.js
test/chartmogul/transaction.js

- Add deprecation info
- Run npm install & eslint
- Change Config interface and bump version

Change Config interface [#35175]

---

README.md
lib/chartmogul.js
lib/chartmogul/contact.js
lib/chartmogul/customer.js
test/chartmogul/contact.js
test/chartmogul/customer.js

This should add support for Contacts (https://dev.chartmogul.com/reference/contacts). Also adds the related items in the Customers resource (https://dev.chartmogul.com/reference/customers).

Support for Contacts

---

package-lock.json
package.json

**Upgraded Package-lock.json to fix vulnerabilties**
1. Prototype Pollution in minimalist vulnerability
2. JSON schema vulnerability
3. Semver vulnerability to regular expression denial of service
4. Prototype Pollution in JSON5 via parse method vulnerability
5. qs vulnerability to prototype pollution
6. mismatch redos vulnerability
7. inefficient tegular expression with ANSI regex
8. tough-cookie prototype pollution vulnerability
9. Path-parse denial of service vulnerability
10. word-wrap vulnerability

Fix security issues(dependent bot)

---

CHANGELOG.md
package-lock.json
package.json

This updates the project's dependencies to address the vulnerability found in Babel: https://github.com/chartmogul/chartmogul-node/security/dependabot/23.

update project dependencies to address Babel vulnerability

---

test/chartmogul/customer.js

Tested manually against live API.

Add website_url to tests

---

CHANGELOG.md
package.json

While tests are very important, it's not necessary to make a new library version, since there are no "production" code bug fixes or features in the commit.

Revert 3.5.0

---

README.md
lib/chartmogul/customer.js
test/chartmogul/customer.js

Story details: https://app.shortcut.com/chartmogul/story/62681
This PR adds support for the customer unmerge API endpoint.

[sc-62681] SDK Unmerge Support - Node

---

CHANGELOG.md
package-lock.json
package.json

**[3.5.0] - 2024-10-24**
- Adds support for unmerging customers

Release v3.5.0

---

CHANGELOG.md
lib/chartmogul/customer.js
package.json
test/chartmogul/customer.js

Story details: https://app.shortcut.com/chartmogul/story/66237
This PR adds support for disconnecting subscriptions.

[sc-66237] Support disconnecting subscriptions in Node library

---

.github/workflows/test.yml
CHANGELOG.md
package-lock.json

Fixes: https://github.com/chartmogul/chartmogul-node/security/dependabot/37
```
* $> npm install
* $> node
* > const ChartMogul = require('./lib/chartmogul')
* > const config = new ChartMogul.Config(API_KEY);
```
* run any command and call .then on the resulting promise

Update packages due to security vulnerability in form-data 4.0.0
